### ISSUE TITLE
Please add Infra team as admins to this repo

### ISSUE THREAD

**Issue by eefahy** [ipfs-shipyard/peer-star-infra#1]
Thanks!

**Comment by victorb** [comment]
I don't see the infra team in the ipfs-shipyard organization. Could you create one with the right members?

Went by https://github.com/orgs/ipfs-shipyard/teams

**Comment by eefahy** [comment]
Ah, right. I can make one if you invite me to the org.

**Comment by victorb** [comment]
>  You've invited eefahy to IPFS Shipyard! They'll be receiving an email shortly. They can also visit https://github.com/ipfs-shipyard to accept the invitation.

**Comment by eefahy** [comment]
Cool - Infra team added to the shipyard org now

**Comment by victorb** [comment]
![image](https://user-images.githubusercontent.com/459764/49606085-59965080-f960-11e8-88c8-1395d0d7c465.png)

Done!
