### ISSUE TITLE
Are these actually needed?

### ISSUE THREAD

**Issue by eefahy** [ipfs-shipyard/peer-star-infra#2]
https://github.com/ipfs-shipyard/peer-star-infra/blob/a7f0317de826d083d5433fd473f4dcec61e520d1/terraform.tfvars.dist#L2-L3

**Comment by eefahy** [comment]
Oh, they are to use the backend? Where's the code that creates that backend?

**Comment by victorb** [comment]
They are used to access the backend. The backend creation is currently not in TF, as it it's a one-time action, but can add the TF config to protocol/infra if that makes sense?

**Comment by eefahy** [comment]
I think it can be included in this repo. You can even use the [backend shared module](https://github.com/protocol/infra-team/tree/master/bootstrap_terraform/shared_modules/backend) from infra-team to make  it.
